<a href="https://colab.research.google.com/github/LeidyDahian/analitica-precio-del-cafe/blob/main/Transformaci%C3%B3n_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random as rnd
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
# hacemos una lista con los años que analizaremos
año = ['2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007','2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009','2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010','2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011','2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012','2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013','2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014','2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015','2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016','2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017','2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018','2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019','2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020','2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021','2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022','2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023','2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024','2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025','2026']

In [ ]:
# creamos el dataframe
df_Cafe = pd.DataFrame(
    {
        "año": año
    }
)
df_Cafe

      año
0    2006
1    2006
2    2006
3    2006
4    2006
..    ...
236  2025
237  2025
238  2025
239  2025
240  2026

[241 rows x 1 columns]

In [ ]:
# importamos el archivo de github que contiene el indice del dolar
url = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/DOLLARINDEX.csv"
df = pd.read_csv(url)
df

          fecha  indice_dolar
0    2006-01-01      100.0000
1    2006-02-01      100.2112
2    2006-03-01      100.4281
3    2006-04-01       99.7435
4    2006-05-01       97.5118
..          ...           ...
236  2025-09-01      120.0291
237  2025-10-01      120.7618
238  2025-11-01      121.4177
239  2025-12-01      120.1883
240  2026-01-01      119.2298

[241 rows x 2 columns]

In [ ]:
df_final_Cafe = pd.concat([df_Cafe, df], axis=1)
df_final_Cafe

      año       fecha  indice_dolar
0    2006  2006-01-01      100.0000
1    2006  2006-02-01      100.2112
2    2006  2006-03-01      100.4281
3    2006  2006-04-01       99.7435
4    2006  2006-05-01       97.5118
..    ...         ...           ...
236  2025  2025-09-01      120.0291
237  2025  2025-10-01      120.7618
238  2025  2025-11-01      121.4177
239  2025  2025-12-01      120.1883
240  2026  2026-01-01      119.2298

[241 rows x 3 columns]

In [ ]:
# importamos el archivo de github que contiene el precio del petroleo
url2 = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/BRENT.csv"
df2 = pd.read_csv(url2)
df2

          fecha  precio_petroleo
0    2006-01-01        63.311818
1    2006-02-01        60.805500
2    2006-03-01        62.746957
3    2006-04-01        70.340000
4    2006-05-01        70.510000
..          ...              ...
236  2025-09-01        67.609091
237  2025-10-01        63.981304
238  2025-11-01        63.693500
239  2025-12-01        61.810909
240  2026-01-01        64.594091

[241 rows x 2 columns]

In [ ]:
df_final_Cafe = pd.merge(df_final_Cafe, df2)
df_final_Cafe

      año       fecha  indice_dolar  precio_petroleo
0    2006  2006-01-01      100.0000        63.311818
1    2006  2006-02-01      100.2112        60.805500
2    2006  2006-03-01      100.4281        62.746957
3    2006  2006-04-01       99.7435        70.340000
4    2006  2006-05-01       97.5118        70.510000
..    ...         ...           ...              ...
236  2025  2025-09-01      120.0291        67.609091
237  2025  2025-10-01      120.7618        63.981304
238  2025  2025-11-01      121.4177        63.693500
239  2025  2025-12-01      120.1883        61.810909
240  2026  2026-01-01      119.2298        64.594091

[241 rows x 4 columns]

In [ ]:
# importamos el archivo de github que contiene el precio de producción
url3 = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/Costo%20de%20produccion.csv"
df3 = pd.read_csv(url3)
df3

          fecha  costo_produccion_cafe
0    2006-01-01                152.300
1    2006-02-01                152.300
2    2006-03-01                152.700
3    2006-04-01                152.700
4    2006-05-01                152.800
..          ...                    ...
236  2025-09-01                359.903
237  2025-10-01                361.677
238  2025-11-01                361.565
239  2025-12-01                364.518
240  2026-01-01                367.200

[241 rows x 2 columns]

In [ ]:
df_final_Cafe = pd.merge(df_final_Cafe, df3)
df_final_Cafe

      año       fecha  indice_dolar  precio_petroleo  costo_produccion_cafe
0    2006  2006-01-01      100.0000        63.311818                152.300
1    2006  2006-02-01      100.2112        60.805500                152.300
2    2006  2006-03-01      100.4281        62.746957                152.700
3    2006  2006-04-01       99.7435        70.340000                152.700
4    2006  2006-05-01       97.5118        70.510000                152.800
..    ...         ...           ...              ...                    ...
236  2025  2025-09-01      120.0291        67.609091                359.903
237  2025  2025-10-01      120.7618        63.981304                361.677
238  2025  2025-11-01      121.4177        63.693500                361.565
239  2025  2025-12-01      120.1883        61.810909                364.518
240  2026  2026-01-01      119.2298        64.594091                367.200

[241 rows x 5 columns]

In [ ]:
# importamos el archivo de github que contiene el precio del cafe en el tiempo
url4 = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/COFFEE.csv"
df4 = pd.read_csv(url4)
df4

          fecha  precio_cafe
0    2006-01-01   124.198636
1    2006-02-01   119.121500
2    2006-03-01   113.660435
3    2006-04-01   115.337500
4    2006-05-01   109.629565
..          ...          ...
236  2025-09-01   399.551364
237  2025-10-01   403.792609
238  2025-11-01   409.679000
239  2025-12-01   380.417273
240  2026-01-01   363.910455

[241 rows x 2 columns]

In [ ]:
df_final_Cafe = pd.merge(df_final_Cafe, df4)
df_final_Cafe

,año,fecha,indice_dolar,precio_petroleo,costo_produccion_cafe,precio_cafe
0,2006,2006-01-01,100.0000,63.311818,152.300,124.198636
1,2006,2006-02-01,100.2112,60.805500,152.300,119.121500
2,2006,2006-03-01,100.4281,62.746957,152.700,113.660435
3,2006,2006-04-01,99.7435,70.340000,152.700,115.337500
4,2006,2006-05-01,97.5118,70.510000,152.800,109.629565
...,...,...,...,...,...,...
236,2025,2025-09-01,120.0291,67.609091,359.903,399.551364
237,2025,2025-10-01,120.7618,63.981304,361.677,403.792609
238,2025,2025-11-01,121.4177,63.693500,361.565,409.679000
239,2025,2025-12-01,120.1883,61.810909,364.518,380.417273
240,2026,2026-01-01,119.2298,64.594091,367.200,363.910455

**Calculo Volatilidad**

In [ ]:
def rendimiento(df_final_Cafe):
    df_final_Cafe["Rendimiento"] =  (df_final_Cafe["precio_cafe"].shift(-1) - df_final_Cafe["precio_cafe"])/ df_final_Cafe["precio_cafe"]
    return df_final_Cafe

In [ ]:
df_final_Cafe = rendimiento(df_final_Cafe)
df_final_Cafe

,año,fecha,indice_dolar,precio_petroleo,costo_produccion_cafe,precio_cafe,Rendimiento
0,2006,2006-01-01,100.0000,63.311818,152.300,124.198636,-0.040879
1,2006,2006-02-01,100.2112,60.805500,152.300,119.121500,-0.045844
2,2006,2006-03-01,100.4281,62.746957,152.700,113.660435,0.014755
3,2006,2006-04-01,99.7435,70.340000,152.700,115.337500,-0.049489
4,2006,2006-05-01,97.5118,70.510000,152.800,109.629565,-0.059108
...,...,...,...,...,...,...,...
236,2025,2025-09-01,120.0291,67.609091,359.903,399.551364,0.010615
237,2025,2025-10-01,120.7618,63.981304,361.677,403.792609,0.014578
238,2025,2025-11-01,121.4177,63.693500,361.565,409.679000,-0.071426
239,2025,2025-12-01,120.1883,61.810909,364.518,380.417273,-0.043391
240,2026,2026-01-01,119.2298,64.594091,367.200,363.910455,NaN

In [ ]:
df_final_Cafe['Promedio rendimiento'] = df_final_Cafe.groupby('año')['Rendimiento'].transform('mean')
df_final_Cafe

,año,fecha,indice_dolar,precio_petroleo,costo_produccion_cafe,precio_cafe,Rendimiento,Promedio rendimiento
0,2006,2006-01-01,100.0000,63.311818,152.300,124.198636,-0.040879,0.001517
1,2006,2006-02-01,100.2112,60.805500,152.300,119.121500,-0.045844,0.001517
2,2006,2006-03-01,100.4281,62.746957,152.700,113.660435,0.014755,0.001517
3,2006,2006-04-01,99.7435,70.340000,152.700,115.337500,-0.049489,0.001517
4,2006,2006-05-01,97.5118,70.510000,152.800,109.629565,-0.059108,0.001517
...,...,...,...,...,...,...,...,...
236,2025,2025-09-01,120.0291,67.609091,359.903,399.551364,0.010615,0.005929
237,2025,2025-10-01,120.7618,63.981304,361.677,403.792609,0.014578,0.005929
238,2025,2025-11-01,121.4177,63.693500,361.565,409.679000,-0.071426,0.005929
239,2025,2025-12-01,120.1883,61.810909,364.518,380.417273,-0.043391,0.005929
240,2026,2026-01-01,119.2298,64.594091,367.200,363.910455,NaN,NaN

In [ ]:
def calcular_diferencia_r(df_final_Cafe):
    df_final_Cafe["Diferencia cuadrado"] = (df_final_Cafe["Rendimiento"]-df_final_Cafe['Promedio rendimiento'])**2
    return df_final_Cafe

# Calculamos la nueva columna usando transform
df_final_Cafe = calcular_diferencia_r(df_final_Cafe)
df_final_Cafe

,año,fecha,indice_dolar,precio_petroleo,costo_produccion_cafe,precio_cafe,Rendimiento,Promedio rendimiento,Diferencia cuadrado
0,2006,2006-01-01,100.0000,63.311818,152.300,124.198636,-0.040879,0.001517,0.001797
1,2006,2006-02-01,100.2112,60.805500,152.300,119.121500,-0.045844,0.001517,0.002243
2,2006,2006-03-01,100.4281,62.746957,152.700,113.660435,0.014755,0.001517,0.000175
3,2006,2006-04-01,99.7435,70.340000,152.700,115.337500,-0.049489,0.001517,0.002602
4,2006,2006-05-01,97.5118,70.510000,152.800,109.629565,-0.059108,0.001517,0.003675
...,...,...,...,...,...,...,...,...,...
236,2025,2025-09-01,120.0291,67.609091,359.903,399.551364,0.010615,0.005929,0.000022
237,2025,2025-10-01,120.7618,63.981304,361.677,403.792609,0.014578,0.005929,0.000075
238,2025,2025-11-01,121.4177,63.693500,361.565,409.679000,-0.071426,0.005929,0.005984
239,2025,2025-12-01,120.1883,61.810909,364.518,380.417273,-0.043391,0.005929,0.002432
240,2026,2026-01-01,119.2298,64.594091,367.200,363.910455,NaN,NaN,NaN

In [ ]:
df_final_Cafe['Suma diferencia cuadrados'] = df_final_Cafe.groupby('año')['Diferencia cuadrado'].transform('sum')
df_final_Cafe

,año,fecha,indice_dolar,precio_petroleo,costo_produccion_cafe,precio_cafe,Rendimiento,Promedio rendimiento,Diferencia cuadrado,Suma diferencia cuadrados
0,2006,2006-01-01,100.0000,63.311818,152.300,124.198636,-0.040879,0.001517,0.001797,0.029033
1,2006,2006-02-01,100.2112,60.805500,152.300,119.121500,-0.045844,0.001517,0.002243,0.029033
2,2006,2006-03-01,100.4281,62.746957,152.700,113.660435,0.014755,0.001517,0.000175,0.029033
3,2006,2006-04-01,99.7435,70.340000,152.700,115.337500,-0.049489,0.001517,0.002602,0.029033
4,2006,2006-05-01,97.5118,70.510000,152.800,109.629565,-0.059108,0.001517,0.003675,0.029033
...,...,...,...,...,...,...,...,...,...,...
236,2025,2025-09-01,120.0291,67.609091,359.903,399.551364,0.010615,0.005929,0.000022,0.088961
237,2025,2025-10-01,120.7618,63.981304,361.677,403.792609,0.014578,0.005929,0.000075,0.088961
238,2025,2025-11-01,121.4177,63.693500,361.565,409.679000,-0.071426,0.005929,0.005984,0.088961
239,2025,2025-12-01,120.1883,61.810909,364.518,380.417273,-0.043391,0.005929,0.002432,0.088961
240,2026,2026-01-01,119.2298,64.594091,367.200,363.910455,NaN,NaN,NaN,0.000000

In [ ]:
def volatilidad(df_final_Cafe):
    df_final_Cafe["Volatilidad"] = np.sqrt((df_final_Cafe['Suma diferencia cuadrados'])/11)
    return df_final_Cafe

# Calculamos la nueva columna usando transform
df_final_Cafe = volatilidad(df_final_Cafe)
df_final_Cafe

,año,fecha,indice_dolar,precio_petroleo,costo_produccion_cafe,precio_cafe,Rendimiento,Promedio rendimiento,Diferencia cuadrado,Suma diferencia cuadrados,Volatilidad
0,2006,2006-01-01,100.0000,63.311818,152.300,124.198636,-0.040879,0.001517,0.001797,0.029033,0.051375
1,2006,2006-02-01,100.2112,60.805500,152.300,119.121500,-0.045844,0.001517,0.002243,0.029033,0.051375
2,2006,2006-03-01,100.4281,62.746957,152.700,113.660435,0.014755,0.001517,0.000175,0.029033,0.051375
3,2006,2006-04-01,99.7435,70.340000,152.700,115.337500,-0.049489,0.001517,0.002602,0.029033,0.051375
4,2006,2006-05-01,97.5118,70.510000,152.800,109.629565,-0.059108,0.001517,0.003675,0.029033,0.051375
...,...,...,...,...,...,...,...,...,...,...,...
236,2025,2025-09-01,120.0291,67.609091,359.903,399.551364,0.010615,0.005929,0.000022,0.088961,0.089930
237,2025,2025-10-01,120.7618,63.981304,361.677,403.792609,0.014578,0.005929,0.000075,0.088961,0.089930
238,2025,2025-11-01,121.4177,63.693500,361.565,409.679000,-0.071426,0.005929,0.005984,0.088961,0.089930
239,2025,2025-12-01,120.1883,61.810909,364.518,380.417273,-0.043391,0.005929,0.002432,0.088961,0.089930
240,2026,2026-01-01,119.2298,64.594091,367.200,363.910455,NaN,NaN,NaN,0.000000,0.000000

In [ ]:
df_Cafe = df_final_Cafe[["año","fecha","indice_dolar","precio_petroleo","costo_produccion_cafe","precio_cafe","Volatilidad"]]
df_Cafe

,año,fecha,indice_dolar,precio_petroleo,costo_produccion_cafe,precio_cafe,Volatilidad
0,2006,2006-01-01,100.0000,63.311818,152.300,124.198636,0.051375
1,2006,2006-02-01,100.2112,60.805500,152.300,119.121500,0.051375
2,2006,2006-03-01,100.4281,62.746957,152.700,113.660435,0.051375
3,2006,2006-04-01,99.7435,70.340000,152.700,115.337500,0.051375
4,2006,2006-05-01,97.5118,70.510000,152.800,109.629565,0.051375
...,...,...,...,...,...,...,...
236,2025,2025-09-01,120.0291,67.609091,359.903,399.551364,0.089930
237,2025,2025-10-01,120.7618,63.981304,361.677,403.792609,0.089930
238,2025,2025-11-01,121.4177,63.693500,361.565,409.679000,0.089930
239,2025,2025-12-01,120.1883,61.810909,364.518,380.417273,0.089930
240,2026,2026-01-01,119.2298,64.594091,367.200,363.910455,0.000000

In [ ]:
df_Cafe.to_csv('datos_cafe.csv', index=False)
files.download('datos_cafe.csv')

**Código consolidado**

In [ ]:
# hacemos una lista con los años que analizaremos
año = ['2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007','2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009','2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010','2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011','2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012','2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013','2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014','2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015','2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016','2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017','2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018','2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019','2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020','2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021','2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022','2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023','2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024','2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025','2026']
# creamos el dataframe
df_Cafe = pd.DataFrame(
    {
        "año": año
    }
)
df_Cafe
# Importamos los archivos desde el github que contienen los diferentes datos
url = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/DOLLARINDEX.csv"
df = pd.read_csv(url)
url2 = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/BRENT.csv"
df2 = pd.read_csv(url2)
url3 = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/Costo%20de%20produccion.csv"
df3 = pd.read_csv(url3)
url4 = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/COFFEE.csv"
df4 = pd.read_csv(url4)
df_final_Cafe = pd.concat([df_Cafe, df], axis=1)
df_final_Cafe = pd.merge(df_final_Cafe, df2)
df_final_Cafe = pd.merge(df_final_Cafe, df3)
df_final_Cafe = pd.merge(df_final_Cafe, df4)
# Calculo volatilidad
def rendimiento(df_final_Cafe):
    df_final_Cafe["Rendimiento"] =  (df_final_Cafe["precio_cafe"].shift(-1) - df_final_Cafe["precio_cafe"])/ df_final_Cafe["precio_cafe"]
    return df_final_Cafe
df_final_Cafe = rendimiento(df_final_Cafe)
df_final_Cafe['Promedio rendimiento'] = df_final_Cafe.groupby('año')['Rendimiento'].transform('mean')

def calcular_diferencia_r(df_final_Cafe):
    df_final_Cafe["Diferencia cuadrado"] = (df_final_Cafe["Rendimiento"]-df_final_Cafe['Promedio rendimiento'])**2
    return df_final_Cafe

# Calculamos la nueva columna
df_final_Cafe = calcular_diferencia_r(df_final_Cafe)
df_final_Cafe['Suma diferencia cuadrados'] = df_final_Cafe.groupby('año')['Diferencia cuadrado'].transform('sum')

def volatilidad(df_final_Cafe):
    df_final_Cafe["Volatilidad"] = np.sqrt((df_final_Cafe['Suma diferencia cuadrados'])/11)
    return df_final_Cafe

# Calculamos la nueva columna
df_final_Cafe = volatilidad(df_final_Cafe)

#Depuración columnas
df_Cafe = df_final_Cafe[["año","fecha","indice_dolar","precio_petroleo","costo_produccion_cafe","precio_cafe","Volatilidad"]]
df_Cafe

#Exportación formato excel
df_Cafe.to_csv('datos_cafe.csv', index=False)
files.download('datos_cafe.csv')